
//#define WORK_DIR "-images-folder" 
#define IMAGE_NAME "-image-name" 
#define WIDTH_BLOCK "-width-block" 
#define HEIGHT_BLOCK "-height-block"
#define FOLDER_RESULT "-folder"
#define EXPORT_RESULT "-export-result"
#define EXPORT_IMAGES "-export-images"
#define SHOW_DATA_SCREEN "-show-data-screen"

#define FORWARD_METHOD "-forward-method"
	#define TORUS_MIX "torus-mixer" 
	#define TURNER_MIX "turner-mixer"
	#define DSJAL_MIX "dsjal-mixer"
	#define FILE_MIX "file-mixer"
	#define JPG_COMPRESSOR "jpg-compressor"
	#define TIBS_COMPRESSOR "tibs-compressor"
	#define AHCR_COMPRESSOR "ahcr-compressor"

#define PACKETIZER_METHOD "-packetizer-method"
	#define NORMAL_PACKETIZER "normal-packetizer" 
	#define FILE_PACKETIZER "file-packetizer" 

#define CHANNEL_METHOD "-channel-method"
	#define LOST_FROM_FILE "lost-from-file"
	#define LOST_BY_ERLANG "lost-erlang"

#define REBUILDER_METHOD "-rebuilder-method"
	#define AVERAGE_RBD "rebuilder-average"
	#define AVERAGE_PIXEL_RBD "rebuilder-average-pixel"
	#define AVERAGE_OPT_RBD "rebuilder-average-opt"
	#define AVERAGE_RAMANBABU2001 "rebuilder-ramanbabu2001"
	#define AVERAGE_CDD "rebuilder-cdd"
    #define AVERAGE_BILI "rebuilder-bili"
    #define AVERAGE_BILIPONDE "rebuilder-biliponde"
    #define AVERAGE_BILIPONDE2 "rebuilder-msr"
    #define AVERAGE_TVBLOCK "rebuilder-tvblock"
    #define AVERAGE_BIC "rebuilder-bic"

#define METRIC "-metric"
   #define METRIC_PSNR "metric-psnr"
